# Data Preprocessing

## Importing Libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


## Importing Dataset

In [2]:
dataset = pd.read_csv('Data.csv')

In [3]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

## Taking care of mising values

In [4]:
from sklearn.impute import SimpleImputer

In [5]:
imputer = SimpleImputer(missing_values = np.nan, strategy='mean')
imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

In [6]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

## Encoding categorical data

In [7]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [8]:
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])],remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [9]:
X

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [10]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [11]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

## Splitting Data

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=1)

In [14]:
X_train

array([[0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 35.0, 58000.0]], dtype=object)

In [15]:
X_test

array([[0.0, 1.0, 0.0, 30.0, 54000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [16]:
y_train

array([0, 1, 0, 0, 1, 1, 0, 1])

In [17]:
y_test

array([0, 1])

## Feature scaling

In [25]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
X_test[:, 3:] = sc.transform(X_test[:, 3:])

In [26]:
X_train

array([[-0.77459667, -0.57735027,  1.29099445, -0.28968847, -1.12163392],
       [-0.77459667,  1.73205081, -0.77459667, -0.07249924, -0.00641122],
       [ 1.29099445, -0.57735027, -0.77459667,  0.63830185,  0.77214048],
       [-0.81649658, -0.5       ,  1.22474487, -0.28559674, -0.33123074],
       [-0.81649658, -0.5       ,  1.22474487, -1.86941741, -1.42109569],
       [ 1.22474487, -0.5       , -0.81649658,  1.15424023,  1.17781303],
       [-0.81649658,  2.        , -0.81649658,  1.44220762,  1.5131561 ],
       [ 1.22474487, -0.5       , -0.81649658, -0.71754784, -0.58273804]])

In [27]:
X_test

array([[-0.77459667,  1.73205081, -0.77459667, -1.84950199, -0.93225648],
       [ 1.29099445, -0.57735027, -0.77459667, -0.60560007,  0.29869688]])